version: '3.8'

services:

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/phonebook?autoReconnect=true&useSSL=false
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-docker
    restart: always
    environment:
      MYSQL_DATABASE: 'phonebook'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    depends_on:
      - app
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mysql-data:
  jenkins-data: